### PR TITLE
Make HiveMetastoreClient cached in a Thread Local way

### LINKED ISSUE #39: TaskEstimator does not cache MetastoreClient connections
Here are the 4 places:
* analyzeTableSpec ([1](https://github.com/airbnb/reair/blob/61d433de146c4e9f04fa324bb3b8794c0ad42911/main/src/main/java/com/airbnb/reair/incremental/primitives/TaskEstimator.java#L79), [2](https://github.com/airbnb/reair/blob/61d433de146c4e9f04fa324bb3b8794c0ad42911/main/src/main/java/com/airbnb/reair/incremental/primitives/TaskEstimator.java#L82))
* analyzePartitionSpec ([1](https://github.com/airbnb/reair/blob/61d433de146c4e9f04fa324bb3b8794c0ad42911/main/src/main/java/com/airbnb/reair/incremental/primitives/TaskEstimator.java#L139), [2](https://github.com/airbnb/reair/blob/61d433de146c4e9f04fa324bb3b8794c0ad42911/main/src/main/java/com/airbnb/reair/incremental/primitives/TaskEstimator.java#L143)).

The result of these is that we are recreating many connections to Hive Metastore in a very short period of time with hundreds of mappers/reducers running concurrently.

We should cache the MetastoreClient connections in a thread-safe way, using ThreadLocal<>.

### PR DESCRIPTION
**Pull request by zshao**
to avoid creating too many connections.

This is to fix #39.

### CODE REVIEW

**Comment by plypaul** [comment]
If it's the case that the connection breaks, there may be parts of the code that assume that calling `getMetastoreClient()` will create a new connection. With the `ThreadLocal` approach, that thread may retry indefinitely. Maybe we need to add a liveness check before returning the connection for this to work?

**Comment by plypaul** [comment]
Looks like there are some checkstyle failures?

**Comment by zshao** [comment]
@plypaul You have a good point.  After looking at the code in more details, I decided to add the auto-reconnect capability into ThriftHiveMetastoreClient.  It's easy to verify the correctness of the code since all logics are captured in ThriftHiveMetastoreClient.

**Comment by plypaul** [comment]
LGTM - thanks @zshao!

**Pull request merged**
