### PR TITLE
the file will on hdfs

### PR DESCRIPTION
**Pull request by hn5092**
if this file   on local ,they will be report inputpath not exist exception

### CODE REVIEW

**Comment by plypaul** [comment]
It should be the case that the input file is uploaded to HDFS for you. Can you post the logs from your run?

**Comment by hn5092** [comment]
1. the file on hdfs  no error:
$hadoop dfs -ls /
DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

Found 10 items
drwxrwxr-x   - hadoop supergroup          0 2016-09-22 10:23 /create
drwxrwxr-x   - hadoop supergroup          0 2016-09-22 12:36 /home
-rw-rw-r--   3 hadoop supergroup        304 2016-09-22 12:36 /reair.keytab
-rw-rw-r--   3 hadoop supergroup         34 2016-09-21 16:27 /table
2.remove the file:
hadoop dfs -rm /table
DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

16/09/23 09:23:49  INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 1440 minutes, Emptier interval = 0 minutes.

3.run it:
16/09/23 09:24:48 INFO hive.MetastoreReplicationJob: Copying /table to temporary directory hdfs://2testpajkcluster/tmp/dest/hive_replication/reair_1474593885840_e120a812-131a-4323-b189-72b3d6af7dc9/table
cp: `/table': No such file or directory
 Input path does not exist: 16/09/23 09:24:50 WARN security.UserGroupInformation: PriviledgedActionException as:hadoop/a1-perf-hadoop-master01.hz@hadoop.com (auth:KERBEROS) cause:org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://2testpajkcluster/tmp/dest/hive_replication/reair_1474593885840_e120a812-131a-4323-b189-72b3d6af7dc9/table
Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://2testpajkcluster/tmp/dest/hive_replication/reair_1474593885840_e120a812-131a-4323-b189-72b3d6af7dc9/table


4.in the source :
 if (localTableListFile.isPresent()) {
            // Create a temporary directory on HDFS and copy our table list to that directory so that it
            // can be read by mappers in the HDFS job.
            Path tableFilePath = localTableListFile.get();
            Path tmpDir = createTempDirectory(getConf());
            tableListFileOnHdfs = Optional.of(new Path(tmpDir, tableFilePath.getName()));
            LOG.info(String.format("Copying %s to temporary directory %s",
                    tableFilePath,
                    tableListFileOnHdfs.get()));
            copyFile(localTableListFile.get(), tableListFileOnHdfs.get());
            LOG.info(String.format("Copied %s to temporary directory %s",
                    tableFilePath,
                    tableListFileOnHdfs.get()));
        } else {
            LOG.info("List of tables to copy is not specified. Copying all tables instead.");
        }

it use hdfs cp cmd ,so  the file must on the hdfs

**Comment by plypaul** [comment]
That's true, it does use `-cp`. However, `Path` should turn into something like `... -cp file:///home/user/empty_file ...`. What do you see when the file is on the local filesystem?

**Comment by hn5092** [comment]
the file on the local is better,so i  think use put  repeat cp better,if need modify ,i need test

**Comment by hn5092** [comment]
i close this and make a new request, replace cp to put

**Pull request closed without merging**
